task:
  name: Test (macOS)
  persistent_worker:
    labels:
      name: dev-mini
    resources:
      tart-vms: 2
  pull_script:
    - tart pull ghcr.io/cirruslabs/macos-sonoma-base:latest
  test_script:
    - go test -v -count=1 ./...
  always:
    cleanup_script:
      - tart list
      - rm -rf ~/.tart/vms/orchard-*

task:
  name: Release Binaries
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Test (macOS)
  env:
    MACOS_SIGN_P12: ENCRYPTED[!183482723ca1a95f9c4439f7a79c9d3b115472bb18c739ed1586e12d3914ccf94ade8169eeda7332fc204f8be9c27d9f!]
    MACOS_SIGN_PASSWORD: ENCRYPTED[!417423346c567f12007f42d084bff1cfee30ee14f7e8258550157679a269c70d541c9f19224224ab0293b10f2c6d4c5e!]
    MACOS_NOTARY_ISSUER_ID: ENCRYPTED[!74076906e9fa36bca3c1da1637b0759b58bb009eb1a707446896eefad3767e8dba1d0f87e71106b98cde98ac4b037a2a!]
    MACOS_NOTARY_KEY_ID: ENCRYPTED[!af9e5da1010a6b04e548ef494acc77a6e0ce176549de98f81c5b5cdd72856de09f77e51cf0849e3c4b7a2d2c22f25ca8!]
    MACOS_NOTARY_KEY: ENCRYPTED[!c70c53f3e6c163931c7cdf9d90aff8934ef21d5dd1090158688e00b94e97c68257d9cf4ae1df873e6ae0d949866aee72!]
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
  container:
    image: goreleaser/goreleaser:latest
    cpu: 4
    memory: 12G
  release_script: goreleaser


docker_builder:
  name: Release Docker Image
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Test (macOS)
  env:
    GITHUB_TOKEN: ENCRYPTED[!82ed873afdf627284305afef4958c85a8f73127b09978a9786ac521559630ea6c9a5ab6e7f8315abf9ead09b6eff6eae!]
  login_script:
    - echo $GITHUB_TOKEN | docker login ghcr.io -u fkorotkov --password-stdin
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  deploy_script: |
    docker buildx build --push --platform linux/amd64,linux/arm64 \
      --tag ghcr.io/cirruslabs/orchard:$CIRRUS_TAG \
      --tag ghcr.io/cirruslabs/orchard:latest \
      .
