version: 2
project_name: orchard

before:
  hooks:
    - go mod download

builds:
  - main: cmd/orchard/main.go
    ldflags: >
      -X github.com/cirruslabs/orchard/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/orchard/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

nfpms:
  - package_name: orchard-controller
    vendor: Cirrus Labs, Inc.
    homepage: https://github.com/cirruslabs/orchard
    maintainer: support@cirruslabs.org
    description: Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices
    section: misc
    formats:
      - deb
      - rpm
    contents:
      - src: packaging/orchard-controller.service
        dst: /lib/systemd/system/orchard-controller.service
        type: config
    scripts:
      postinstall: packaging/postinstall.sh
      preremove: packaging/preremove.sh
      postremove: packaging/postremove.sh

furies:
  - account: cirruslabs

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"

brews:
  - name: orchard
    ids:
      - regular
    repository:
      owner: cirruslabs
      name: homebrew-cli
    install: |
      bin.install "orchard"
      generate_completions_from_executable(bin/"orchard", "completion")
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/orchard
    description: Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices
    skip_upload: auto
