// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: orchard.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*WatchInstruction_PortForwardAction
	//	*WatchInstruction_SyncVmsAction
	Action isWatchInstruction_Action `protobuf_oneof:"action"`
}

func (x *WatchInstruction) Reset() {
	*x = WatchInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInstruction) ProtoMessage() {}

func (x *WatchInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInstruction.ProtoReflect.Descriptor instead.
func (*WatchInstruction) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0}
}

func (m *WatchInstruction) GetAction() isWatchInstruction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *WatchInstruction) GetPortForwardAction() *WatchInstruction_PortForward {
	if x, ok := x.GetAction().(*WatchInstruction_PortForwardAction); ok {
		return x.PortForwardAction
	}
	return nil
}

func (x *WatchInstruction) GetSyncVmsAction() *WatchInstruction_SyncVMs {
	if x, ok := x.GetAction().(*WatchInstruction_SyncVmsAction); ok {
		return x.SyncVmsAction
	}
	return nil
}

type isWatchInstruction_Action interface {
	isWatchInstruction_Action()
}

type WatchInstruction_PortForwardAction struct {
	PortForwardAction *WatchInstruction_PortForward `protobuf:"bytes,1,opt,name=port_forward_action,json=portForwardAction,proto3,oneof"`
}

type WatchInstruction_SyncVmsAction struct {
	SyncVmsAction *WatchInstruction_SyncVMs `protobuf:"bytes,2,opt,name=sync_vms_action,json=syncVmsAction,proto3,oneof"`
}

func (*WatchInstruction_PortForwardAction) isWatchInstruction_Action() {}

func (*WatchInstruction_SyncVmsAction) isWatchInstruction_Action() {}

type PortForwardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PortForwardData) Reset() {
	*x = PortForwardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardData) ProtoMessage() {}

func (x *PortForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardData.ProtoReflect.Descriptor instead.
func (*PortForwardData) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{1}
}

func (x *PortForwardData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WatchInstruction_PortForward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// we can have multiple port forwards for the same vm/port pair
	// let's distinguish them by a unique session
	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// can be empty to request a forwarding to the worker itself
	VmUid string `protobuf:"bytes,2,opt,name=vm_uid,json=vmUid,proto3" json:"vm_uid,omitempty"`
	Port  uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *WatchInstruction_PortForward) Reset() {
	*x = WatchInstruction_PortForward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchInstruction_PortForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInstruction_PortForward) ProtoMessage() {}

func (x *WatchInstruction_PortForward) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInstruction_PortForward.ProtoReflect.Descriptor instead.
func (*WatchInstruction_PortForward) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WatchInstruction_PortForward) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *WatchInstruction_PortForward) GetVmUid() string {
	if x != nil {
		return x.VmUid
	}
	return ""
}

func (x *WatchInstruction_PortForward) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type WatchInstruction_SyncVMs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatchInstruction_SyncVMs) Reset() {
	*x = WatchInstruction_SyncVMs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchInstruction_SyncVMs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInstruction_SyncVMs) ProtoMessage() {}

func (x *WatchInstruction_SyncVMs) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInstruction_SyncVMs.ProtoReflect.Descriptor instead.
func (*WatchInstruction_SyncVMs) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0, 1}
}

var File_orchard_proto protoreflect.FileDescriptor

var file_orchard_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x72, 0x63, 0x68, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x02, 0x0a,
	0x10, 0x57, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x4f, 0x0a, 0x13, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52,
	0x11, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x76, 0x6d, 0x73, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x56, 0x4d, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x56, 0x6d,
	0x73, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x52, 0x0a, 0x0b, 0x50, 0x6f, 0x72, 0x74, 0x46,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x15, 0x0a, 0x06, 0x76, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x09, 0x0a, 0x07, 0x53,
	0x79, 0x6e, 0x63, 0x56, 0x4d, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x25, 0x0a, 0x0f, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x79, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x0b, 0x50,
	0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x10, 0x2e, 0x50, 0x6f, 0x72,
	0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x10, 0x2e, 0x50,
	0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x69, 0x72, 0x72, 0x75, 0x73, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x6f, 0x72, 0x63, 0x68,
	0x61, 0x72, 0x64, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orchard_proto_rawDescOnce sync.Once
	file_orchard_proto_rawDescData = file_orchard_proto_rawDesc
)

func file_orchard_proto_rawDescGZIP() []byte {
	file_orchard_proto_rawDescOnce.Do(func() {
		file_orchard_proto_rawDescData = protoimpl.X.CompressGZIP(file_orchard_proto_rawDescData)
	})
	return file_orchard_proto_rawDescData
}

var file_orchard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orchard_proto_goTypes = []interface{}{
	(*WatchInstruction)(nil),             // 0: WatchInstruction
	(*PortForwardData)(nil),              // 1: PortForwardData
	(*WatchInstruction_PortForward)(nil), // 2: WatchInstruction.PortForward
	(*WatchInstruction_SyncVMs)(nil),     // 3: WatchInstruction.SyncVMs
	(*emptypb.Empty)(nil),                // 4: google.protobuf.Empty
}
var file_orchard_proto_depIdxs = []int32{
	2, // 0: WatchInstruction.port_forward_action:type_name -> WatchInstruction.PortForward
	3, // 1: WatchInstruction.sync_vms_action:type_name -> WatchInstruction.SyncVMs
	4, // 2: Controller.Watch:input_type -> google.protobuf.Empty
	1, // 3: Controller.PortForward:input_type -> PortForwardData
	0, // 4: Controller.Watch:output_type -> WatchInstruction
	1, // 5: Controller.PortForward:output_type -> PortForwardData
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orchard_proto_init() }
func file_orchard_proto_init() {
	if File_orchard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orchard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortForwardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchInstruction_PortForward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchInstruction_SyncVMs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_orchard_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*WatchInstruction_PortForwardAction)(nil),
		(*WatchInstruction_SyncVmsAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orchard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchard_proto_goTypes,
		DependencyIndexes: file_orchard_proto_depIdxs,
		MessageInfos:      file_orchard_proto_msgTypes,
	}.Build()
	File_orchard_proto = out.File
	file_orchard_proto_rawDesc = nil
	file_orchard_proto_goTypes = nil
	file_orchard_proto_depIdxs = nil
}
