// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: orchard.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollFromWorker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*PollFromWorker_InitAction
	Action isPollFromWorker_Action `protobuf_oneof:"action"`
}

func (x *PollFromWorker) Reset() {
	*x = PollFromWorker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollFromWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollFromWorker) ProtoMessage() {}

func (x *PollFromWorker) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollFromWorker.ProtoReflect.Descriptor instead.
func (*PollFromWorker) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0}
}

func (m *PollFromWorker) GetAction() isPollFromWorker_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *PollFromWorker) GetInitAction() *PollFromWorker_Init {
	if x, ok := x.GetAction().(*PollFromWorker_InitAction); ok {
		return x.InitAction
	}
	return nil
}

type isPollFromWorker_Action interface {
	isPollFromWorker_Action()
}

type PollFromWorker_InitAction struct {
	InitAction *PollFromWorker_Init `protobuf:"bytes,1,opt,name=init_action,json=initAction,proto3,oneof"`
}

func (*PollFromWorker_InitAction) isPollFromWorker_Action() {}

type PollFromController struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*PollFromController_PortForwardAction
	Action isPollFromController_Action `protobuf_oneof:"action"`
}

func (x *PollFromController) Reset() {
	*x = PollFromController{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollFromController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollFromController) ProtoMessage() {}

func (x *PollFromController) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollFromController.ProtoReflect.Descriptor instead.
func (*PollFromController) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{1}
}

func (m *PollFromController) GetAction() isPollFromController_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *PollFromController) GetPortForwardAction() *PollFromController_PortForward {
	if x, ok := x.GetAction().(*PollFromController_PortForwardAction); ok {
		return x.PortForwardAction
	}
	return nil
}

type isPollFromController_Action interface {
	isPollFromController_Action()
}

type PollFromController_PortForwardAction struct {
	PortForwardAction *PollFromController_PortForward `protobuf:"bytes,1,opt,name=port_forward_action,json=portForwardAction,proto3,oneof"`
}

func (*PollFromController_PortForwardAction) isPollFromController_Action() {}

type PortForwardFromWorker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*PortForwardFromWorker_InitAction
	//	*PortForwardFromWorker_DataAction
	Action isPortForwardFromWorker_Action `protobuf_oneof:"action"`
}

func (x *PortForwardFromWorker) Reset() {
	*x = PortForwardFromWorker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortForwardFromWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardFromWorker) ProtoMessage() {}

func (x *PortForwardFromWorker) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardFromWorker.ProtoReflect.Descriptor instead.
func (*PortForwardFromWorker) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{2}
}

func (m *PortForwardFromWorker) GetAction() isPortForwardFromWorker_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *PortForwardFromWorker) GetInitAction() *PortForwardFromWorker_Init {
	if x, ok := x.GetAction().(*PortForwardFromWorker_InitAction); ok {
		return x.InitAction
	}
	return nil
}

func (x *PortForwardFromWorker) GetDataAction() *PortForwardFromWorker_Data {
	if x, ok := x.GetAction().(*PortForwardFromWorker_DataAction); ok {
		return x.DataAction
	}
	return nil
}

type isPortForwardFromWorker_Action interface {
	isPortForwardFromWorker_Action()
}

type PortForwardFromWorker_InitAction struct {
	InitAction *PortForwardFromWorker_Init `protobuf:"bytes,1,opt,name=init_action,json=initAction,proto3,oneof"`
}

type PortForwardFromWorker_DataAction struct {
	DataAction *PortForwardFromWorker_Data `protobuf:"bytes,2,opt,name=data_action,json=dataAction,proto3,oneof"`
}

func (*PortForwardFromWorker_InitAction) isPortForwardFromWorker_Action() {}

func (*PortForwardFromWorker_DataAction) isPortForwardFromWorker_Action() {}

type PortForwardFromController struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*PortForwardFromController_DataAction
	Action isPortForwardFromController_Action `protobuf_oneof:"action"`
}

func (x *PortForwardFromController) Reset() {
	*x = PortForwardFromController{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortForwardFromController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardFromController) ProtoMessage() {}

func (x *PortForwardFromController) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardFromController.ProtoReflect.Descriptor instead.
func (*PortForwardFromController) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{3}
}

func (m *PortForwardFromController) GetAction() isPortForwardFromController_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *PortForwardFromController) GetDataAction() *PortForwardFromController_Data {
	if x, ok := x.GetAction().(*PortForwardFromController_DataAction); ok {
		return x.DataAction
	}
	return nil
}

type isPortForwardFromController_Action interface {
	isPortForwardFromController_Action()
}

type PortForwardFromController_DataAction struct {
	DataAction *PortForwardFromController_Data `protobuf:"bytes,1,opt,name=data_action,json=dataAction,proto3,oneof"`
}

func (*PortForwardFromController_DataAction) isPortForwardFromController_Action() {}

type PollFromWorker_Init struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerUid string `protobuf:"bytes,1,opt,name=worker_uid,json=workerUid,proto3" json:"worker_uid,omitempty"`
}

func (x *PollFromWorker_Init) Reset() {
	*x = PollFromWorker_Init{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollFromWorker_Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollFromWorker_Init) ProtoMessage() {}

func (x *PollFromWorker_Init) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollFromWorker_Init.ProtoReflect.Descriptor instead.
func (*PollFromWorker_Init) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PollFromWorker_Init) GetWorkerUid() string {
	if x != nil {
		return x.WorkerUid
	}
	return ""
}

type PollFromController_PortForward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VmUid  string `protobuf:"bytes,2,opt,name=vm_uid,json=vmUid,proto3" json:"vm_uid,omitempty"`
	VmPort uint32 `protobuf:"varint,3,opt,name=vm_port,json=vmPort,proto3" json:"vm_port,omitempty"`
}

func (x *PollFromController_PortForward) Reset() {
	*x = PollFromController_PortForward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollFromController_PortForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollFromController_PortForward) ProtoMessage() {}

func (x *PollFromController_PortForward) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollFromController_PortForward.ProtoReflect.Descriptor instead.
func (*PollFromController_PortForward) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PollFromController_PortForward) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PollFromController_PortForward) GetVmUid() string {
	if x != nil {
		return x.VmUid
	}
	return ""
}

func (x *PollFromController_PortForward) GetVmPort() uint32 {
	if x != nil {
		return x.VmPort
	}
	return 0
}

type PortForwardFromWorker_Init struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *PortForwardFromWorker_Init) Reset() {
	*x = PortForwardFromWorker_Init{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortForwardFromWorker_Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardFromWorker_Init) ProtoMessage() {}

func (x *PortForwardFromWorker_Init) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardFromWorker_Init.ProtoReflect.Descriptor instead.
func (*PortForwardFromWorker_Init) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PortForwardFromWorker_Init) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PortForwardFromWorker_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PortForwardFromWorker_Data) Reset() {
	*x = PortForwardFromWorker_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortForwardFromWorker_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardFromWorker_Data) ProtoMessage() {}

func (x *PortForwardFromWorker_Data) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardFromWorker_Data.ProtoReflect.Descriptor instead.
func (*PortForwardFromWorker_Data) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{2, 1}
}

func (x *PortForwardFromWorker_Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PortForwardFromController_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PortForwardFromController_Data) Reset() {
	*x = PortForwardFromController_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchard_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortForwardFromController_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardFromController_Data) ProtoMessage() {}

func (x *PortForwardFromController_Data) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardFromController_Data.ProtoReflect.Descriptor instead.
func (*PortForwardFromController_Data) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{3, 0}
}

func (x *PortForwardFromController_Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_orchard_proto protoreflect.FileDescriptor

var file_orchard_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x72, 0x63, 0x68, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7a, 0x0a, 0x0e, 0x50, 0x6f, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x12, 0x37, 0x0a, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x46, 0x72, 0x6f,
	0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x00, 0x52, 0x0a,
	0x69, 0x6e, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x25, 0x0a, 0x04, 0x49, 0x6e,
	0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x55, 0x69,
	0x64, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc6, 0x01, 0x0a, 0x12,
	0x50, 0x6f, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x51, 0x0a, 0x13, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x48, 0x00, 0x52, 0x11, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x53, 0x0a, 0x0b, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x6d,
	0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x6d, 0x55, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6d, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x76, 0x6d, 0x50, 0x6f, 0x72, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xdb, 0x01, 0x0a, 0x15, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x3e,
	0x0a, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e,
	0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1c,
	0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x1a, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x19, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x12, 0x42, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x85, 0x01, 0x0a, 0x0a, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x04, 0x50, 0x6f, 0x6c,
	0x6c, 0x12, 0x0f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x1a, 0x13, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x28, 0x01, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0b, 0x50,
	0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x16, 0x2e, 0x50, 0x6f, 0x72,
	0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x69, 0x72, 0x72, 0x75, 0x73, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x6f, 0x72, 0x63, 0x68,
	0x61, 0x72, 0x64, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orchard_proto_rawDescOnce sync.Once
	file_orchard_proto_rawDescData = file_orchard_proto_rawDesc
)

func file_orchard_proto_rawDescGZIP() []byte {
	file_orchard_proto_rawDescOnce.Do(func() {
		file_orchard_proto_rawDescData = protoimpl.X.CompressGZIP(file_orchard_proto_rawDescData)
	})
	return file_orchard_proto_rawDescData
}

var file_orchard_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orchard_proto_goTypes = []interface{}{
	(*PollFromWorker)(nil),                 // 0: PollFromWorker
	(*PollFromController)(nil),             // 1: PollFromController
	(*PortForwardFromWorker)(nil),          // 2: PortForwardFromWorker
	(*PortForwardFromController)(nil),      // 3: PortForwardFromController
	(*PollFromWorker_Init)(nil),            // 4: PollFromWorker.Init
	(*PollFromController_PortForward)(nil), // 5: PollFromController.PortForward
	(*PortForwardFromWorker_Init)(nil),     // 6: PortForwardFromWorker.Init
	(*PortForwardFromWorker_Data)(nil),     // 7: PortForwardFromWorker.Data
	(*PortForwardFromController_Data)(nil), // 8: PortForwardFromController.Data
}
var file_orchard_proto_depIdxs = []int32{
	4, // 0: PollFromWorker.init_action:type_name -> PollFromWorker.Init
	5, // 1: PollFromController.port_forward_action:type_name -> PollFromController.PortForward
	6, // 2: PortForwardFromWorker.init_action:type_name -> PortForwardFromWorker.Init
	7, // 3: PortForwardFromWorker.data_action:type_name -> PortForwardFromWorker.Data
	8, // 4: PortForwardFromController.data_action:type_name -> PortForwardFromController.Data
	0, // 5: Controller.Poll:input_type -> PollFromWorker
	2, // 6: Controller.PortForward:input_type -> PortForwardFromWorker
	1, // 7: Controller.Poll:output_type -> PollFromController
	3, // 8: Controller.PortForward:output_type -> PortForwardFromController
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_orchard_proto_init() }
func file_orchard_proto_init() {
	if File_orchard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orchard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollFromWorker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollFromController); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortForwardFromWorker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortForwardFromController); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollFromWorker_Init); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollFromController_PortForward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortForwardFromWorker_Init); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortForwardFromWorker_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchard_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortForwardFromController_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_orchard_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PollFromWorker_InitAction)(nil),
	}
	file_orchard_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PollFromController_PortForwardAction)(nil),
	}
	file_orchard_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*PortForwardFromWorker_InitAction)(nil),
		(*PortForwardFromWorker_DataAction)(nil),
	}
	file_orchard_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*PortForwardFromController_DataAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orchard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchard_proto_goTypes,
		DependencyIndexes: file_orchard_proto_depIdxs,
		MessageInfos:      file_orchard_proto_msgTypes,
	}.Build()
	File_orchard_proto = out.File
	file_orchard_proto_rawDesc = nil
	file_orchard_proto_goTypes = nil
	file_orchard_proto_depIdxs = nil
}
