// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: guestagent/guestagent.proto

package guestagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ExecRequest_Command_
	//	*ExecRequest_StandardInput
	//	*ExecRequest_TerminalResize
	Type          isExecRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_guestagent_guestagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guestagent_guestagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_guestagent_guestagent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetType() isExecRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ExecRequest) GetCommand() *ExecRequest_Command {
	if x != nil {
		if x, ok := x.Type.(*ExecRequest_Command_); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ExecRequest) GetStandardInput() *IOChunk {
	if x != nil {
		if x, ok := x.Type.(*ExecRequest_StandardInput); ok {
			return x.StandardInput
		}
	}
	return nil
}

func (x *ExecRequest) GetTerminalResize() *TerminalSize {
	if x != nil {
		if x, ok := x.Type.(*ExecRequest_TerminalResize); ok {
			return x.TerminalResize
		}
	}
	return nil
}

type isExecRequest_Type interface {
	isExecRequest_Type()
}

type ExecRequest_Command_ struct {
	Command *ExecRequest_Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ExecRequest_StandardInput struct {
	StandardInput *IOChunk `protobuf:"bytes,2,opt,name=standard_input,json=standardInput,proto3,oneof"`
}

type ExecRequest_TerminalResize struct {
	TerminalResize *TerminalSize `protobuf:"bytes,3,opt,name=terminal_resize,json=terminalResize,proto3,oneof"`
}

func (*ExecRequest_Command_) isExecRequest_Type() {}

func (*ExecRequest_StandardInput) isExecRequest_Type() {}

func (*ExecRequest_TerminalResize) isExecRequest_Type() {}

type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ExecResponse_Exit_
	//	*ExecResponse_StandardOutput
	//	*ExecResponse_StandardError
	Type          isExecResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_guestagent_guestagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guestagent_guestagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_guestagent_guestagent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetType() isExecResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ExecResponse) GetExit() *ExecResponse_Exit {
	if x != nil {
		if x, ok := x.Type.(*ExecResponse_Exit_); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *ExecResponse) GetStandardOutput() *IOChunk {
	if x != nil {
		if x, ok := x.Type.(*ExecResponse_StandardOutput); ok {
			return x.StandardOutput
		}
	}
	return nil
}

func (x *ExecResponse) GetStandardError() *IOChunk {
	if x != nil {
		if x, ok := x.Type.(*ExecResponse_StandardError); ok {
			return x.StandardError
		}
	}
	return nil
}

type isExecResponse_Type interface {
	isExecResponse_Type()
}

type ExecResponse_Exit_ struct {
	Exit *ExecResponse_Exit `protobuf:"bytes,1,opt,name=exit,proto3,oneof"`
}

type ExecResponse_StandardOutput struct {
	StandardOutput *IOChunk `protobuf:"bytes,2,opt,name=standard_output,json=standardOutput,proto3,oneof"`
}

type ExecResponse_StandardError struct {
	StandardError *IOChunk `protobuf:"bytes,3,opt,name=standard_error,json=standardError,proto3,oneof"`
}

func (*ExecResponse_Exit_) isExecResponse_Type() {}

func (*ExecResponse_StandardOutput) isExecResponse_Type() {}

func (*ExecResponse_StandardError) isExecResponse_Type() {}

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_guestagent_guestagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_guestagent_guestagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_guestagent_guestagent_proto_rawDescGZIP(), []int{2}
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type IOChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOChunk) Reset() {
	*x = IOChunk{}
	mi := &file_guestagent_guestagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOChunk) ProtoMessage() {}

func (x *IOChunk) ProtoReflect() protoreflect.Message {
	mi := &file_guestagent_guestagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOChunk.ProtoReflect.Descriptor instead.
func (*IOChunk) Descriptor() ([]byte, []int) {
	return file_guestagent_guestagent_proto_rawDescGZIP(), []int{3}
}

func (x *IOChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIPRequest) Reset() {
	*x = ResolveIPRequest{}
	mi := &file_guestagent_guestagent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIPRequest) ProtoMessage() {}

func (x *ResolveIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guestagent_guestagent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIPRequest.ProtoReflect.Descriptor instead.
func (*ResolveIPRequest) Descriptor() ([]byte, []int) {
	return file_guestagent_guestagent_proto_rawDescGZIP(), []int{4}
}

type ResolveIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIPResponse) Reset() {
	*x = ResolveIPResponse{}
	mi := &file_guestagent_guestagent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIPResponse) ProtoMessage() {}

func (x *ResolveIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guestagent_guestagent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIPResponse.ProtoReflect.Descriptor instead.
func (*ResolveIPResponse) Descriptor() ([]byte, []int) {
	return file_guestagent_guestagent_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveIPResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ExecRequest_Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Interactive   bool                   `protobuf:"varint,3,opt,name=interactive,proto3" json:"interactive,omitempty"`
	Tty           bool                   `protobuf:"varint,4,opt,name=tty,proto3" json:"tty,omitempty"`
	TerminalSize  *TerminalSize          `protobuf:"bytes,5,opt,name=terminal_size,json=terminalSize,proto3" json:"terminal_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest_Command) Reset() {
	*x = ExecRequest_Command{}
	mi := &file_guestagent_guestagent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest_Command) ProtoMessage() {}

func (x *ExecRequest_Command) ProtoReflect() protoreflect.Message {
	mi := &file_guestagent_guestagent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest_Command.ProtoReflect.Descriptor instead.
func (*ExecRequest_Command) Descriptor() ([]byte, []int) {
	return file_guestagent_guestagent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ExecRequest_Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecRequest_Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest_Command) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *ExecRequest_Command) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecRequest_Command) GetTerminalSize() *TerminalSize {
	if x != nil {
		return x.TerminalSize
	}
	return nil
}

type ExecResponse_Exit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse_Exit) Reset() {
	*x = ExecResponse_Exit{}
	mi := &file_guestagent_guestagent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse_Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse_Exit) ProtoMessage() {}

func (x *ExecResponse_Exit) ProtoReflect() protoreflect.Message {
	mi := &file_guestagent_guestagent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse_Exit.ProtoReflect.Descriptor instead.
func (*ExecResponse_Exit) Descriptor() ([]byte, []int) {
	return file_guestagent_guestagent_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ExecResponse_Exit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_guestagent_guestagent_proto protoreflect.FileDescriptor

const file_guestagent_guestagent_proto_rawDesc = "" +
	"\n" +
	"\x1bguestagent/guestagent.proto\x12\n" +
	"guestagent\"\xfc\x02\n" +
	"\vExecRequest\x12;\n" +
	"\acommand\x18\x01 \x01(\v2\x1f.guestagent.ExecRequest.CommandH\x00R\acommand\x12<\n" +
	"\x0estandard_input\x18\x02 \x01(\v2\x13.guestagent.IOChunkH\x00R\rstandardInput\x12C\n" +
	"\x0fterminal_resize\x18\x03 \x01(\v2\x18.guestagent.TerminalSizeH\x00R\x0eterminalResize\x1a\xa4\x01\n" +
	"\aCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12 \n" +
	"\vinteractive\x18\x03 \x01(\bR\vinteractive\x12\x10\n" +
	"\x03tty\x18\x04 \x01(\bR\x03tty\x12=\n" +
	"\rterminal_size\x18\x05 \x01(\v2\x18.guestagent.TerminalSizeR\fterminalSizeB\x06\n" +
	"\x04type\"\xe5\x01\n" +
	"\fExecResponse\x123\n" +
	"\x04exit\x18\x01 \x01(\v2\x1d.guestagent.ExecResponse.ExitH\x00R\x04exit\x12>\n" +
	"\x0fstandard_output\x18\x02 \x01(\v2\x13.guestagent.IOChunkH\x00R\x0estandardOutput\x12<\n" +
	"\x0estandard_error\x18\x03 \x01(\v2\x13.guestagent.IOChunkH\x00R\rstandardError\x1a\x1a\n" +
	"\x04Exit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04codeB\x06\n" +
	"\x04type\"6\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"\x1d\n" +
	"\aIOChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x12\n" +
	"\x10ResolveIPRequest\"#\n" +
	"\x11ResolveIPResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip2\x90\x01\n" +
	"\x05Agent\x12=\n" +
	"\x04Exec\x12\x17.guestagent.ExecRequest\x1a\x18.guestagent.ExecResponse(\x010\x01\x12H\n" +
	"\tResolveIP\x12\x1c.guestagent.ResolveIPRequest\x1a\x1d.guestagent.ResolveIPResponseB.Z,github.com/cirruslabs/orchard/rpc/guestagentb\x06proto3"

var (
	file_guestagent_guestagent_proto_rawDescOnce sync.Once
	file_guestagent_guestagent_proto_rawDescData []byte
)

func file_guestagent_guestagent_proto_rawDescGZIP() []byte {
	file_guestagent_guestagent_proto_rawDescOnce.Do(func() {
		file_guestagent_guestagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guestagent_guestagent_proto_rawDesc), len(file_guestagent_guestagent_proto_rawDesc)))
	})
	return file_guestagent_guestagent_proto_rawDescData
}

var file_guestagent_guestagent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_guestagent_guestagent_proto_goTypes = []any{
	(*ExecRequest)(nil),         // 0: guestagent.ExecRequest
	(*ExecResponse)(nil),        // 1: guestagent.ExecResponse
	(*TerminalSize)(nil),        // 2: guestagent.TerminalSize
	(*IOChunk)(nil),             // 3: guestagent.IOChunk
	(*ResolveIPRequest)(nil),    // 4: guestagent.ResolveIPRequest
	(*ResolveIPResponse)(nil),   // 5: guestagent.ResolveIPResponse
	(*ExecRequest_Command)(nil), // 6: guestagent.ExecRequest.Command
	(*ExecResponse_Exit)(nil),   // 7: guestagent.ExecResponse.Exit
}
var file_guestagent_guestagent_proto_depIdxs = []int32{
	6, // 0: guestagent.ExecRequest.command:type_name -> guestagent.ExecRequest.Command
	3, // 1: guestagent.ExecRequest.standard_input:type_name -> guestagent.IOChunk
	2, // 2: guestagent.ExecRequest.terminal_resize:type_name -> guestagent.TerminalSize
	7, // 3: guestagent.ExecResponse.exit:type_name -> guestagent.ExecResponse.Exit
	3, // 4: guestagent.ExecResponse.standard_output:type_name -> guestagent.IOChunk
	3, // 5: guestagent.ExecResponse.standard_error:type_name -> guestagent.IOChunk
	2, // 6: guestagent.ExecRequest.Command.terminal_size:type_name -> guestagent.TerminalSize
	0, // 7: guestagent.Agent.Exec:input_type -> guestagent.ExecRequest
	4, // 8: guestagent.Agent.ResolveIP:input_type -> guestagent.ResolveIPRequest
	1, // 9: guestagent.Agent.Exec:output_type -> guestagent.ExecResponse
	5, // 10: guestagent.Agent.ResolveIP:output_type -> guestagent.ResolveIPResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_guestagent_guestagent_proto_init() }
func file_guestagent_guestagent_proto_init() {
	if File_guestagent_guestagent_proto != nil {
		return
	}
	file_guestagent_guestagent_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecRequest_Command_)(nil),
		(*ExecRequest_StandardInput)(nil),
		(*ExecRequest_TerminalResize)(nil),
	}
	file_guestagent_guestagent_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecResponse_Exit_)(nil),
		(*ExecResponse_StandardOutput)(nil),
		(*ExecResponse_StandardError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guestagent_guestagent_proto_rawDesc), len(file_guestagent_guestagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guestagent_guestagent_proto_goTypes,
		DependencyIndexes: file_guestagent_guestagent_proto_depIdxs,
		MessageInfos:      file_guestagent_guestagent_proto_msgTypes,
	}.Build()
	File_guestagent_guestagent_proto = out.File
	file_guestagent_guestagent_proto_goTypes = nil
	file_guestagent_guestagent_proto_depIdxs = nil
}
