name: Main

on:
  push:

jobs:
  test:
    name: Test (Linux)
    runs-on: ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-md
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Vetu
        run: |
          sudo apt-get update && sudo apt-get -y install apt-transport-https ca-certificates
          echo "deb [trusted=yes] https://apt.fury.io/cirruslabs/ /" | sudo tee /etc/apt/sources.list.d/cirruslabs.list
          sudo apt-get update && sudo apt-get -y install vetu
      - name: Pre-pull default Vetu image for use in tests
        run: |
          vetu pull ghcr.io/cirruslabs/ubuntu-runner-amd64:latest
      - name: Run tests
        run: go test -v -count=1 ./...
